{application,main,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{main_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[generate_data,main_app,main_sup,task1]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
